print(f"My name is Sam Allen and here is my CS120 Mad Lib Project!")
print(f"The date is 8/19/2024.")
print(f"This project is designed to take various inputs from users and turn them into an output. This output should resemble a coherent mad lib game based on the poem “Where the Sidewalk Ends” by Shel Silverstein. ")
print(f" ")
userName = input("What's your name? ")
scent = input("Please tell me your favorite scent. ")
noun1 = input("Please give me a noun. ")
noun2 = input("Please give me another noun. ")
verb1 = input("Now give me a verb. ")
verb2 = input("Next give me another verb. ")
verb3 = input("Please give me just one more verb! ")
adjective1 = input("Please give me an adjective. ")
adjective2 = input("Please give me another adjective. ")
color = input("Please tell me your least favorite color. ")
print(f"Seriously? You don't like {color}? ")
thing = input("Never mind, just name me a thing, please. ")
animal = input("Now name an animal. ")
pluralAnimal = input("Next, please give me a plural animal name. ")
pronoun = input("I know, I know, just a couple more, hang in there! Please give me a singular, possessive pronoun. ")
plant = input("Please give me a singular plant. ")
pluralPlant = input("Last one! I just need a plural plant name, please. ")
speed = input("Alright, I lied, but this is actually it. Please name a speed and then we'll be done. ")
print(f" ")
print(f"'Where the {noun1} Ends' by {userName}.")
print(f" ")
print(f"There is a place where the {noun1} ends")
print(f"And before the {noun2} begins,")
print(f"And there the {plant} grows {adjective1} and {adjective2},")
print(f"And there the {thing} burns crimson bright,")
print(f"And there the {animal} rests from {pronoun} flight")
print(f"To {verb1} in the {scent} wind.")
print(f" ")
print(f"Let us {verb2} this place where the smoke blows {color}")
print(f"And the dark {noun2} winds and bends. ")
print(f"Past the pits where the asphalt {pluralPlant} grow")
print(f"We shall {verb3} with a {verb3} that is measured and {speed}, ")
print(f"And watch where the chalk-{color} arrows go")
print(f"To the place where the {noun1} ends.")
print(f" ")
print(f"Yes we'll {verb3} with a {verb3} that is measured and {speed},")
print(f"And we'll go where the chalk-{color} arrows go,")
print(f"For the {pluralAnimal}, they mark, and the {pluralAnimal}, they know")
print(f"The place where the {noun1} ends.")